MvcNetCoreLinqToSqlInjection/Models/Coche.cs
namespace MvcNetCoreLinqToSqlInjection.Models
{
    public class Coche : ICoche
    {
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        public int Velocidad { get; set; }
        public int VelocidadMaxima { get; set; }

        public Coche()
        {

        }

        public void Acelerar()
        {
            this.Velocidad += 20;
            if (this.Velocidad >= this.VelocidadMaxima)
            {
                this.Velocidad = this.VelocidadMaxima;
            }
        }
        public void Frenar()
        {
            this.Velocidad -= 20;
            if (this.Velocidad < 0)
            {
                this.Velocidad = 0;
            }
        }
    }
}

MvcNetCoreLinqToSqlInjection/Models/Deportivo.cs
namespace MvcNetCoreLinqToSqlInjection.Models
{
    public class Deportivo : ICoche
    {
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
        public int Velocidad { get; set; }
        public int VelocidadMaxima { get; set; }
        public Deportivo()
        {
            this.Marca = "Batmovil";
            this.Modelo = "1989";
            this.Imagen = "Batmobile-1989.jpg";
            this.Velocidad = 0;
            this.VelocidadMaxima = 320;
        }


        public void Acelerar()
        {
            this.Velocidad += 45;
            if (this.Velocidad >= this.VelocidadMaxima)
            {
                this.Velocidad = this.VelocidadMaxima;
            }
        }

        public void Frenar()
        {
            this.Velocidad -= 15;
            if (this.Velocidad < 0)
            {
                this.Velocidad = 0;
            }
        }

    }
}

MvcNetCoreLinqToSqlInjection/Models/Doctor.cs
namespace MvcNetCoreLinqToSqlInjection.Models
{
    public class Doctor
    {
        public int IdDoctor { get; set; }
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
        public int Salario { get; set; }
        public int IdHospital { get; set; }
    }
}

MvcNetCoreLinqToSqlInjection/Models/ErrorViewModel.cs
namespace MvcNetCoreLinqToSqlInjection.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreLinqToSqlInjection/Models/ICoche.cs
namespace MvcNetCoreLinqToSqlInjection.Models
{
    public interface ICoche
    {
        string Marca { get; set; }
        string Modelo { get; set; }
        string Imagen { get; set; }
        int Velocidad { get; set; }
        int VelocidadMaxima { get; set; }

        void Acelerar();
        void Frenar();

    }
}

MvcNetCoreLinqToSqlInjection/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSqlInjection.Models;
namespace MvcNetCoreLinqToSqlInjection.Controllers
{
    public class CochesController : Controller
    {
        private ICoche car;
        public CochesController(ICoche car)
        {
            this.car = car;
        }
        public IActionResult Index()
        {
            return View(this.car);
        }

        [HttpPost]
        public IActionResult Index(string accion)
        {
            if (accion.ToLower() == "acelerar")
            {
                this.car.Acelerar();
            }
            else if (accion.ToLower() == "frenar")
            {
                this.car.Frenar();
            }
            return View(this.car);
        }
    }
}

MvcNetCoreLinqToSqlInjection/Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSqlInjection.Models;
using MvcNetCoreLinqToSqlInjection.Repositories;

namespace MvcNetCoreLinqToSqlInjection.Controllers
{
    public class DoctoresController : Controller
    {
        private IRepositoryDoctores repo;

        public DoctoresController(IRepositoryDoctores repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Doctor> doctors = this.repo.GetDoctores();
            return View(doctors);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Doctor doc)
        {
            await this.repo.CreateDoctorAsync(doc.IdDoctor, doc.Apellido, doc.Especialidad, doc.Salario, doc.IdHospital);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(Doctor doc)
        {
            await this.repo.UpdateDoctorAsync(doc.IdDoctor, doc.Apellido, doc.Especialidad, doc.Salario, doc.IdHospital);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int idDoctor)
        {
            Doctor doc = this.repo.FindDoctor(idDoctor);
            return View(doc);
        }

        public async Task<IActionResult> Delete(int iddoctor)
        {
            await this.repo.DeleteDoctorAsync(iddoctor);
            return RedirectToAction("Index");
        }

        public IActionResult DoctoresEspecialidad()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }
        [HttpPost]
        public IActionResult DoctoresEspecialidad(string especialidad)
        {
            List<Doctor> doctores = this.repo.GetDoctoresEspecialidad(especialidad);
            return View(doctores);
        }
    }
}

MvcNetCoreLinqToSqlInjection/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSqlInjection.Models;

namespace MvcNetCoreLinqToSqlInjection.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreLinqToSqlInjection/Views/Coches/Index.cshtml
@model ICoche

<h1 style="color:blue">@Model.Marca @Model.Modelo</h1>
<h2 style="">Velocidad actual: 
    <span style="color:green">@Model.Velocidad</span>
</h2>
<h1>
    Velocidad Máxima:
    <span style="color:red">@Model.VelocidadMaxima</span>
</h1>

<form method="post">
    <button name="accion" value="acelerar" class="btn btn-warning">Acelerar</button>
    <button name="accion" value="frenar" class="btn btn-warning">Frenar</button>
</form>

<img src="/images/@Model.Imagen" 
style="width: 350px; height: 300px"/>

MvcNetCoreLinqToSqlInjection/Views/Doctores/Create.cshtml
<p>
    <a asp-controller="Doctores" asp-action="Index">
       Back to List
    </a>
</p>

<form method="post">
    <label>Id</label>
    <input type="text" name="idDoctor" class="form-control"/>
    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" />
    <label>Especialidad</label>
    <input type="text" name="especialidad" class="form-control" />
    <label>Salario</label>
    <input type="text" name="salario" class="form-control" />
    <label>IdHospital</label>
    <input type="text" name="idHospital" class="form-control" />
    <button class="btn btn-primary">Crear</button>
</form>

MvcNetCoreLinqToSqlInjection/Views/Doctores/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MvcNetCoreLinqToSqlInjection/Views/Doctores/DoctoresEspecialidad.cshtml
@model List<Doctor>
<h1>Doctores especialidad</h1>

<form method="post">
    <label>Introduzca especialidad</label>
    <input type="text" name="especialidad" class="form-control" />
    <button class="btn btn-warning">
        Buscar doctores
    </button>
</form>

<table class="table table-info">
    <thead>
        <tr>
            <th>Apellidos</th>
            <th>Especialidad</th>
            <th>Salario</th>

        </tr>
    </thead>
    <tbody>
        @foreach(Doctor doctor in Model)
        {
            <tr>
                <td>@doctor.Apellido</td>
                <td>@doctor.Especialidad</td>
                <td>@doctor.Salario</td>
            </tr>
        }
    </tbody>
</table>

MvcNetCoreLinqToSqlInjection/Views/Doctores/Index.cshtml
@model List<Doctor>

<a asp-controller="Doctores" asp-action="Create" class="btn btn-primary">Crear</a>
<table class="table table-dark">
    <thead>
        <th>Id</th>
        <th>Apellido</th>
        <th>Especialidad</th>
        <th>Salario</th>
        <th>Hospital</th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
        @if(Model != null)
        {
            @foreach(Doctor doctor in Model)
            {
                <tr>
                    <td>@doctor.IdDoctor</td>
                    <td>@doctor.Apellido</td>
                    <td>@doctor.Especialidad</td>
                    <td>@doctor.Salario</td>
                    <td>@doctor.IdHospital</td>
                    <td>
                        <a asp-action="Delete" asp-controller="Doctores" asp-route-iddoctor="@doctor.IdDoctor" class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                    <td>
                        <a asp-action="Update" asp-controller="Doctores" asp-route-idDoctor="@doctor.IdDoctor" class="btn btn-info">
                            Update
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

MvcNetCoreLinqToSqlInjection/Views/Doctores/Update.cshtml
@model Doctor
<p>
    <a asp-controller="Doctores" asp-action="Index">
        Back to List
    </a>
</p>

<form method="post">
    <label>Id</label>
    <input type="text" name="idDoctor" class="form-control" value="@Model.IdDoctor" readonly/>
    <label>Apellido</label>
    <input type="text" name="apellido" class="form-control" value="@Model.Apellido"/>
    <label>Especialidad</label>
    <input type="text" name="especialidad" class="form-control" value="@Model.Especialidad" />
    <label>Salario</label>
    <input type="text" name="salario" class="form-control" value="@Model.Salario" />
    <label>IdHospital</label>
    <input type="text" name="idHospital" class="form-control" value="@Model.IdHospital" />
    <button class="btn btn-primary">Editar</button>
</form>

MvcNetCoreLinqToSqlInjection/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreLinqToSqlInjection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreLinqToSqlInjection</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreLinqToSqlInjection.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreLinqToSqlInjection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Coches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="Index">Doctores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="DoctoresEspecialidad">Doctores Especilidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcNetCoreLinqToSqlInjection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>